all: tket.tds.zip

tket.tds.zip: doc/tket-doc.pdf
	mkdir -p tket.tds/doc/tex/latex/tket
	cp doc/tket-doc.pdf doc/*.tex tket.tds/doc/tex/latex/tket
	mkdir -p tket.tds/tex/latex/tket
	cp src/*.eps src/*.pdf src/tket.sty tket.tds/tex/latex/tket
	zip -r tket.tds.zip tket.tds
	rm -r tket.tds

doc/tket-doc.pdf: %.pdf: %.tex
	latexmk -cd -pdf -shell-escape -deps-out=$*.d $*.tex

# File containing dependencies, generated by latexmk
doc/tket-doc.d: %.d: %.tex
	latexmk -cd -pdf -shell-escape -deps-out=$*.d $*.tex
	# Adjust paths
	sed -i -e 's@^\( *\)\([^\\# /]\)@\1doc/\2@' $@
	# Remove dependencies inadvertently picked up from minted by latexmk
	sed -i -e 's@$*\.\(aex\|w18\)@@' $@

include doc/tket-doc.d
